---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice2
  namespace: microservices
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
spec:
  selector:
    matchLabels:
      app: emailservice2
  template:
    metadata:
      labels:
        app: emailservice2
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    spec:
      automountServiceAccountToken: false
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext:
        runAsUser: 15000
      containers:
      - name: server
        image: gcr.io/google-samples/microservices-demo/emailservice@sha256:387ce5121c47edbc33b0c607d50963d5a8f4af82ef9604e6f0341322b06c7a4d
        imagePullPolicy: Always
        securityContext:
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
...
